### GET all products
GET http://localhost:3000/products

###

### Create product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "lipstick",
  "price": 200,
  "quantity": 4
}

###

### GET product by id
GET http://localhost:3000/products/1779791547298

###

### Update product
PATCH http://localhost:3000/products/1779791547298
Content-Type: application/json

{
  "name": "eye brow pencil"
}

###

### Delete product
DELETE http://localhost:3000/products/1779791547298

###

### Filter by name
GET http://localhost:3000/products?name=Lipstick